import {
  Card,
  Popover,
  ActionList,
  Button,
  TextContainer,
  ResourceList,
  List,
} from '@shopify/polaris'

const CardDashboard1 = ({ ideas }) => {
  const sumIdeasValue = ideas.reduce((a, { value }) => a + value, 0)
  return (
    <div>
      <Card
        secondaryFooterActions={[
          { content: 'Results', url: '/dashboard/results' },
        ]}
        primaryFooterAction={{
          content: 'Add Idea',
          url: '/dashboard/ideas/new',
        }}
      >
        <Card.Header
          actions={[
            {
              content: 'Total Sales',
            },
          ]}
          title="Ideas"
        >
          <Popover
            active={false}
            activator={
              <Button disclosure plain>
                View Sales
              </Button>
            }
            onClose={() => {}}
          >
            <ActionList
              items={[{ content: 'Gross Sales' }, { content: 'Net Sales' }]}
            />
          </Popover>
        </Card.Header>
        <Card.Section>
          <TextContainer>
            You can use this report to see the ideas generated by your
            organisation.
          </TextContainer>
        </Card.Section>
        <Card.Section title="Number of Ideas and cost reduction Value">
          <ResourceList
            resourceName={{ singular: 'sale', plural: 'sales' }}
            items={[
              {
                sales: 'Orders',
                amount: 'USD$0.00',
                url: 'reports/orders',
              },
              {
                sales: 'Returns',
                amount: '-USD$250.00',
                url: 'reports/returns',
              },
            ]}
            renderItem={(item) => {
              const { sales, amount, url } = item
              return (
                <p>
                  {ideas.length}, {sumIdeasValue}
                </p>
              )
            }}
          />
        </Card.Section>
        <Card.Section title="Ideas in Progress" subdued>
          <List>
            <List.Item>Number of active tasks</List.Item>
            <List.Item>Total value in progress</List.Item>
          </List>
        </Card.Section>
        <Card.Section title="Total cost reduction accomplished">
          <TextContainer>Total cost reduction accomplished</TextContainer>
        </Card.Section>
      </Card>
    </div>
  )
}

export default CardDashboard1
