const CardDashboard1 = ({ ideas, tasks }) => {
  const sumIdeasValue = ideas.reduce((a, { value }) => a + value, 0)
  const activeIdeas = ideas.filter((x) => x.active)
  const sumTasksValue = activeIdeas.reduce((a, { value }) => a + value, 0)
  return (
    <div>
      You can use this report to see the{' '}
      <span className="font-semibold">ideas</span> generated by your
      organisation, <span className="font-semibold">value in progress</span> and{' '}
      <span className="font-semibold">actual</span> results.
    </div>
  )
}

export default CardDashboard1
