import { Card, Popover, Button, TextContainer, List } from '@shopify/polaris'

const CardDashboard1 = ({ ideas, tasks }) => {
  const sumIdeasValue = ideas.reduce((a, { value }) => a + value, 0)
  const activeIdeas = ideas.filter((x) => x.active)
  const sumTasksValue = activeIdeas.reduce((a, { value }) => a + value, 0)
  return (
    <div>
      <Card
        secondaryFooterActions={[
          { content: 'Results', url: '/dashboard/results' },
        ]}
        primaryFooterAction={{
          content: 'Add Idea',
          url: '/dashboard/ideas/new',
        }}
      >
        <Card.Header title="Overview">
          <Popover
            active={false}
            activator={
              <Button disclosure plain>
                View Results
              </Button>
            }
            onClose={() => {}}
          ></Popover>
        </Card.Header>
        <Card.Section>
          <TextContainer>
            You can use this report to see the{' '}
            <span className="font-semibold">ideas</span> generated by your
            organisation,{' '}
            <span className="font-semibold">value in progress</span> and{' '}
            <span className="font-semibold">actual</span> results.
          </TextContainer>
        </Card.Section>
        <Card.Section title="Ideas generated">
          <List>
            <List.Item>Number of Ideas</List.Item>
            <p>{ideas.length}</p>
            <List.Item>Total ideas value</List.Item>
            <p>
              {sumIdeasValue.toLocaleString('en-US', {
                style: 'currency',
                currency: 'USD',
              })}
            </p>
          </List>
        </Card.Section>
        <Card.Section title="Tasks in Progress" subdued>
          <List>
            <List.Item>Number of active tasks</List.Item>
            <p>{tasks.length}</p>
            <List.Item>Total value in progress</List.Item>
            <p>
              {sumTasksValue.toLocaleString('en-US', {
                style: 'currency',
                currency: 'USD',
              })}
            </p>
          </List>
        </Card.Section>
        <Card.Section title="Cost reduction accomplished">
          <List>
            <List.Item>Number of ideas completed</List.Item>
            <p>0</p>
            <List.Item>Total cost reduction value</List.Item>
            <p>0$</p>
          </List>
        </Card.Section>
      </Card>
    </div>
  )
}

export default CardDashboard1
